apiVersion: v1
kind: Service
metadata:
  name: synapse-broker-headless
  namespace: {{ .Namespace }}
spec:
  clusterIP: None
  selector:
    app: broker
  ports:
    - name: raft
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-broker-client
  namespace: {{ .Namespace }}
spec:
  selector:
    app: broker
  ports:
    - name: client
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: synapse-broker
  namespace: {{ .Namespace }}
spec:
  serviceName: "synapse-broker-headless"
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: broker
        image: synapse-broker:latest
        imagePullPolicy: Never
        env:
        - name: BROKER_PORT
          value: "8080"
        - name: BROKER_FILEPATH
          value: "/data"
        - name: RAFT_PORT
          value: "8081"
        - name: REPLICAS
          value: "{{ .Replicas }}"
        - name: STATEFULSET_NAME
          value: "synapse-broker"
        - name: HEADLESS_SVC
          value: "synapse-broker-headless.{{ .Namespace }}.svc.cluster.local"
        - name: METRICS_PORT
          value: "8082"
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8080
          name: client
        - containerPort: 8081
          name: raft
        - containerPort: 8082
          name: metrics
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 128Mi
