apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .HandlerName }}
  labels:
    app: {{ .HandlerName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .HandlerName }}
  template:
    metadata:
      labels:
        app: {{ .HandlerName }}
    spec:
      containers:
      - name: main-container
        image: synapse-handlers:latest       
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .HandlerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .HandlerName }}-service
spec:
  selector:
    app: {{ .HandlerName }}
  ports:
    - protocol: TCP
      port: {{ .HandlerPort }}
      targetPort: {{ .HandlerPort }}